import { spawn } from 'node:child_process';
import { join } from 'node:path';
import { createRequire } from 'node:module';
const require = createRequire(new URL('../../bench/package.json', import.meta.url));
const { chromium } = require('playwright-core');
const ROOT = new URL('.', import.meta.url).pathname;
const server = spawn(process.execPath, [join(ROOT, 'serve.mjs'), process.argv[2]], { stdio: ['ignore', 'pipe', 'inherit'] });
const url = await new Promise((r) => server.stdout.once('data', (d) => r(String(d).trim())));
const browser = await chromium.launch({ executablePath: '/usr/bin/google-chrome', args: ['--enable-gpu', '--use-angle=vulkan', '--enable-features=Vulkan', '--ignore-gpu-blocklist', '--enable-unsafe-webgpu'] });
const page = await browser.newPage({ viewport: { width: 900, height: 300 } });
const logs = [];
page.on('console', (m) => { if (!/limits=|preferred|404/.test(m.text())) logs.push(`${m.type()}: ${m.text().slice(0, 300)}`); });
page.on('pageerror', (e) => logs.push(`pageerror: ${e.message}`));
await page.goto(url);
await page.waitForFunction(() => window.__herdrPaintedRevision > 0, null, { timeout: 30000 });
await page.mouse.click(450, 150);
await page.keyboard.press('Control+Shift+F');
await page.waitForTimeout(300);
await page.keyboard.type('line');
await page.waitForTimeout(800);
await page.screenshot({ path: join(ROOT, 'shot-debug-find.png') });
console.log('events:', JSON.stringify(await page.evaluate(() => window.__herdrEvents)));
await page.keyboard.press('Escape');
await page.waitForTimeout(300);
await page.keyboard.type('echo after');
await page.keyboard.press('Enter');
await page.waitForTimeout(500);
console.log(logs.join('\n'));
await browser.close(); server.kill();
