//! Provider logos from CodexBar (MIT), monochrome so they tint like the
//! other embedded icons. See `assets/icons/providers/README.md`.

pub(crate) static PROVIDER_ICONS: &[(&str, &[u8])] = &[
    (
        "icons/providers/codex.svg",
        include_bytes!("../../../../assets/icons/providers/codex.svg"),
    ),
    (
        "icons/providers/claude.svg",
        include_bytes!("../../../../assets/icons/providers/claude.svg"),
    ),
    (
        "icons/providers/clinepass.svg",
        include_bytes!("../../../../assets/icons/providers/clinepass.svg"),
    ),
    (
        "icons/providers/cursor.svg",
        include_bytes!("../../../../assets/icons/providers/cursor.svg"),
    ),
    (
        "icons/providers/opencode.svg",
        include_bytes!("../../../../assets/icons/providers/opencode.svg"),
    ),
    (
        "icons/providers/opencodego.svg",
        include_bytes!("../../../../assets/icons/providers/opencodego.svg"),
    ),
    (
        "icons/providers/alibaba.svg",
        include_bytes!("../../../../assets/icons/providers/alibaba.svg"),
    ),
    (
        "icons/providers/qwencloud.svg",
        include_bytes!("../../../../assets/icons/providers/qwencloud.svg"),
    ),
    (
        "icons/providers/factory.svg",
        include_bytes!("../../../../assets/icons/providers/factory.svg"),
    ),
    (
        "icons/providers/fireworks.svg",
        include_bytes!("../../../../assets/icons/providers/fireworks.svg"),
    ),
    (
        "icons/providers/gemini.svg",
        include_bytes!("../../../../assets/icons/providers/gemini.svg"),
    ),
    (
        "icons/providers/antigravity.svg",
        include_bytes!("../../../../assets/icons/providers/antigravity.svg"),
    ),
    (
        "icons/providers/copilot.svg",
        include_bytes!("../../../../assets/icons/providers/copilot.svg"),
    ),
    (
        "icons/providers/devin.svg",
        include_bytes!("../../../../assets/icons/providers/devin.svg"),
    ),
    (
        "icons/providers/zai.svg",
        include_bytes!("../../../../assets/icons/providers/zai.svg"),
    ),
    (
        "icons/providers/minimax.svg",
        include_bytes!("../../../../assets/icons/providers/minimax.svg"),
    ),
    (
        "icons/providers/manus.svg",
        include_bytes!("../../../../assets/icons/providers/manus.svg"),
    ),
    (
        "icons/providers/kimi.svg",
        include_bytes!("../../../../assets/icons/providers/kimi.svg"),
    ),
    (
        "icons/providers/kilo.svg",
        include_bytes!("../../../../assets/icons/providers/kilo.svg"),
    ),
    (
        "icons/providers/kiro.svg",
        include_bytes!("../../../../assets/icons/providers/kiro.svg"),
    ),
    (
        "icons/providers/vertexai.svg",
        include_bytes!("../../../../assets/icons/providers/vertexai.svg"),
    ),
    (
        "icons/providers/augment.svg",
        include_bytes!("../../../../assets/icons/providers/augment.svg"),
    ),
    (
        "icons/providers/jetbrains.svg",
        include_bytes!("../../../../assets/icons/providers/jetbrains.svg"),
    ),
    (
        "icons/providers/amp.svg",
        include_bytes!("../../../../assets/icons/providers/amp.svg"),
    ),
    (
        "icons/providers/t3chat.svg",
        include_bytes!("../../../../assets/icons/providers/t3chat.svg"),
    ),
    (
        "icons/providers/ollama.svg",
        include_bytes!("../../../../assets/icons/providers/ollama.svg"),
    ),
    (
        "icons/providers/synthetic.svg",
        include_bytes!("../../../../assets/icons/providers/synthetic.svg"),
    ),
    (
        "icons/providers/openrouter.svg",
        include_bytes!("../../../../assets/icons/providers/openrouter.svg"),
    ),
    (
        "icons/providers/elevenlabs.svg",
        include_bytes!("../../../../assets/icons/providers/elevenlabs.svg"),
    ),
    (
        "icons/providers/warp.svg",
        include_bytes!("../../../../assets/icons/providers/warp.svg"),
    ),
    (
        "icons/providers/windsurf.svg",
        include_bytes!("../../../../assets/icons/providers/windsurf.svg"),
    ),
    (
        "icons/providers/zed.svg",
        include_bytes!("../../../../assets/icons/providers/zed.svg"),
    ),
    (
        "icons/providers/perplexity.svg",
        include_bytes!("../../../../assets/icons/providers/perplexity.svg"),
    ),
    (
        "icons/providers/mimo.svg",
        include_bytes!("../../../../assets/icons/providers/mimo.svg"),
    ),
    (
        "icons/providers/doubao.svg",
        include_bytes!("../../../../assets/icons/providers/doubao.svg"),
    ),
    (
        "icons/providers/sakana.svg",
        include_bytes!("../../../../assets/icons/providers/sakana.svg"),
    ),
    (
        "icons/providers/abacus.svg",
        include_bytes!("../../../../assets/icons/providers/abacus.svg"),
    ),
    (
        "icons/providers/mistral.svg",
        include_bytes!("../../../../assets/icons/providers/mistral.svg"),
    ),
    (
        "icons/providers/deepseek.svg",
        include_bytes!("../../../../assets/icons/providers/deepseek.svg"),
    ),
    (
        "icons/providers/deepinfra.svg",
        include_bytes!("../../../../assets/icons/providers/deepinfra.svg"),
    ),
    (
        "icons/providers/codebuff.svg",
        include_bytes!("../../../../assets/icons/providers/codebuff.svg"),
    ),
    (
        "icons/providers/venice.svg",
        include_bytes!("../../../../assets/icons/providers/venice.svg"),
    ),
    (
        "icons/providers/commandcode.svg",
        include_bytes!("../../../../assets/icons/providers/commandcode.svg"),
    ),
    (
        "icons/providers/qoder.svg",
        include_bytes!("../../../../assets/icons/providers/qoder.svg"),
    ),
    (
        "icons/providers/stepfun.svg",
        include_bytes!("../../../../assets/icons/providers/stepfun.svg"),
    ),
    (
        "icons/providers/bedrock.svg",
        include_bytes!("../../../../assets/icons/providers/bedrock.svg"),
    ),
    (
        "icons/providers/grok.svg",
        include_bytes!("../../../../assets/icons/providers/grok.svg"),
    ),
    (
        "icons/providers/groq.svg",
        include_bytes!("../../../../assets/icons/providers/groq.svg"),
    ),
    (
        "icons/providers/llmproxy.svg",
        include_bytes!("../../../../assets/icons/providers/llmproxy.svg"),
    ),
    (
        "icons/providers/litellm.svg",
        include_bytes!("../../../../assets/icons/providers/litellm.svg"),
    ),
    (
        "icons/providers/bifrost.svg",
        include_bytes!("../../../../assets/icons/providers/bifrost.svg"),
    ),
    (
        "icons/providers/aixy.svg",
        include_bytes!("../../../../assets/icons/providers/aixy.svg"),
    ),
    (
        "icons/providers/deepgram.svg",
        include_bytes!("../../../../assets/icons/providers/deepgram.svg"),
    ),
    (
        "icons/providers/poe.svg",
        include_bytes!("../../../../assets/icons/providers/poe.svg"),
    ),
    (
        "icons/providers/chutes.svg",
        include_bytes!("../../../../assets/icons/providers/chutes.svg"),
    ),
    (
        "icons/providers/neuralwatt.svg",
        include_bytes!("../../../../assets/icons/providers/neuralwatt.svg"),
    ),
    (
        "icons/providers/helmcode.svg",
        include_bytes!("../../../../assets/icons/providers/helmcode.svg"),
    ),
    (
        "icons/providers/clawrouter.svg",
        include_bytes!("../../../../assets/icons/providers/clawrouter.svg"),
    ),
    (
        "icons/providers/longcat.svg",
        include_bytes!("../../../../assets/icons/providers/longcat.svg"),
    ),
    (
        "icons/providers/sub2api.svg",
        include_bytes!("../../../../assets/icons/providers/sub2api.svg"),
    ),
    (
        "icons/providers/wayfinder.svg",
        include_bytes!("../../../../assets/icons/providers/wayfinder.svg"),
    ),
    (
        "icons/providers/zenmux.svg",
        include_bytes!("../../../../assets/icons/providers/zenmux.svg"),
    ),
    (
        "icons/providers/aiand.svg",
        include_bytes!("../../../../assets/icons/providers/aiand.svg"),
    ),
    (
        "icons/providers/zoommate.svg",
        include_bytes!("../../../../assets/icons/providers/zoommate.svg"),
    ),
    (
        "icons/providers/xai.svg",
        include_bytes!("../../../../assets/icons/providers/xai.svg"),
    ),
    (
        "icons/providers/notion.svg",
        include_bytes!("../../../../assets/icons/providers/notion.svg"),
    ),
    (
        "icons/providers/ibmbob.svg",
        include_bytes!("../../../../assets/icons/providers/ibmbob.svg"),
    ),
    (
        "icons/providers/nous.svg",
        include_bytes!("../../../../assets/icons/providers/nous.svg"),
    ),
    (
        "icons/providers/muse.svg",
        include_bytes!("../../../../assets/icons/providers/muse.svg"),
    ),
    (
        "icons/providers/coderabbit.svg",
        include_bytes!("../../../../assets/icons/providers/coderabbit.svg"),
    ),
    (
        "icons/providers/replicate.svg",
        include_bytes!("../../../../assets/icons/providers/replicate.svg"),
    ),
    (
        "icons/providers/huggingface.svg",
        include_bytes!("../../../../assets/icons/providers/huggingface.svg"),
    ),
    (
        "icons/providers/raycast.svg",
        include_bytes!("../../../../assets/icons/providers/raycast.svg"),
    ),
    (
        "icons/providers/pi.svg",
        include_bytes!("../../../../assets/icons/providers/pi.svg"),
    ),
    (
        "icons/providers/v0.svg",
        include_bytes!("../../../../assets/icons/providers/v0.svg"),
    ),
    (
        "icons/providers/typesafe.svg",
        include_bytes!("../../../../assets/icons/providers/typesafe.svg"),
    ),
    (
        "icons/providers/hyper.svg",
        include_bytes!("../../../../assets/icons/providers/hyper.svg"),
    ),
    (
        "icons/providers/gitkraken.svg",
        include_bytes!("../../../../assets/icons/providers/gitkraken.svg"),
    ),
    (
        "icons/providers/devpass.svg",
        include_bytes!("../../../../assets/icons/providers/devpass.svg"),
    ),
    (
        "icons/providers/atlascloud.svg",
        include_bytes!("../../../../assets/icons/providers/atlascloud.svg"),
    ),
    (
        "icons/providers/vercel.svg",
        include_bytes!("../../../../assets/icons/providers/vercel.svg"),
    ),
    (
        "icons/providers/llmman.svg",
        include_bytes!("../../../../assets/icons/providers/llmman.svg"),
    ),
    (
        "icons/providers/xkiro.svg",
        include_bytes!("../../../../assets/icons/providers/xkiro.svg"),
    ),
];

/// The logo for a provider id, when one ships.
pub(crate) fn for_id(id: &str) -> Option<&'static str> {
    PROVIDER_ICONS.iter().map(|(path, _)| *path).find(|path| {
        path.strip_prefix("icons/providers/")
            .and_then(|file| file.strip_suffix(".svg"))
            == Some(id)
    })
}
