#![allow(clippy::unwrap_used, clippy::expect_used)]

use herdr_protocol::*;

#[test]
fn independent_clipboard_fixture_preserves_field_and_variant_order() {
    // Hand-written bincode 2 standard: message tag 2, target tag 1, pane ID,
    // extension, vector length, opaque bytes. Not generated by our wire model.
    let fixture = [
        15, 0, 0, 0, 2, 1, 2, b'p', b'1', 3, b'p', b'n', b'g', 5, 137, 80, 78, 71, 13,
    ];
    let encoded = encode_clipboard_image(
        ClientClipboardImageTarget::Pane("p1".into()),
        "png",
        vec![137, 80, 78, 71, 13],
    )
    .unwrap();
    assert_eq!(encoded, fixture);
    for (tag, target) in [
        (0, ClientClipboardImageTarget::DirectTerminal),
        (1, ClientClipboardImageTarget::Pane("p1".into())),
        (2, ClientClipboardImageTarget::Popup("t1".into())),
    ] {
        let encoded = encode_clipboard_image(target.clone(), "png", vec![137]).unwrap();
        assert_eq!(encoded[4..6], [2, tag]);
        assert_eq!(
            read_message::<_, ClientMessage>(
                &mut encoded.as_slice(),
                MAX_CLIPBOARD_IMAGE_FRAME_SIZE
            )
            .unwrap(),
            ClientMessage::ClipboardImage {
                target,
                extension: "png".into(),
                data: vec![137]
            }
        );
    }
}

#[test]
fn image_bounds_do_not_relax_normal_frame_cap() {
    for size in [MAX_FRAME_SIZE + 1, MAX_CLIPBOARD_IMAGE_PAYLOAD] {
        let encoded = encode_clipboard_image(
            ClientClipboardImageTarget::Pane("x".repeat(MAX_CLIPBOARD_IMAGE_TARGET_BYTES)),
            "png",
            vec![42; size],
        )
        .unwrap();
        assert!(encoded.len() - 4 <= MAX_CLIPBOARD_IMAGE_FRAME_SIZE);
        assert!(matches!(
            read_message::<_, ClientMessage>(&mut encoded.as_slice(), MAX_FRAME_SIZE),
            Err(Error::FrameLimit)
        ));
        let decoded: ClientMessage =
            read_message(&mut encoded.as_slice(), MAX_CLIPBOARD_IMAGE_FRAME_SIZE).unwrap();
        assert!(
            matches!(&decoded, ClientMessage::ClipboardImage { data, .. } if data.len() == size)
        );
        assert!(encode_message(&decoded, MAX_FRAME_SIZE).is_err());
    }
    for data in [vec![], vec![0; MAX_CLIPBOARD_IMAGE_PAYLOAD + 1]] {
        assert!(matches!(
            encode_clipboard_image(ClientClipboardImageTarget::DirectTerminal, "png", data),
            Err(Error::ClipboardImageSize)
        ));
    }
}

#[test]
fn extensions_and_targets_are_bounded_and_validated() {
    for extension in ["png", "PNG", "jpg", "jpeg", "JPEG", "gif", "webp", "bmp"] {
        let bytes = encode_clipboard_image(
            ClientClipboardImageTarget::DirectTerminal,
            extension,
            vec![1],
        )
        .unwrap();
        let decoded: ClientMessage =
            read_message(&mut bytes.as_slice(), MAX_CLIPBOARD_IMAGE_FRAME_SIZE).unwrap();
        let expected = if extension.eq_ignore_ascii_case("jpeg") {
            "jpg".into()
        } else {
            extension.to_ascii_lowercase()
        };
        assert!(
            matches!(decoded, ClientMessage::ClipboardImage { extension, .. } if extension == expected)
        );
    }
    for extension in ["", "svg", ".png", "image/png", "png\0", "../png", " png"] {
        assert!(matches!(
            encode_clipboard_image(
                ClientClipboardImageTarget::DirectTerminal,
                extension,
                vec![1]
            ),
            Err(Error::ClipboardImageExtension)
        ));
    }
    for id in [
        String::new(),
        "x".repeat(MAX_CLIPBOARD_IMAGE_TARGET_BYTES + 1),
    ] {
        for target in [
            ClientClipboardImageTarget::Pane(id.clone()),
            ClientClipboardImageTarget::Popup(id.clone()),
        ] {
            assert!(matches!(
                validate_clipboard_image_target(&target),
                Err(Error::ClipboardImageTarget)
            ));
        }
    }
}
