#![allow(clippy::unwrap_used, clippy::expect_used)]

use herdr_protocol::*;

fn payload(message: &ClientMessage) -> Vec<u8> {
    encode_message(message, MAX_FRAME_SIZE).unwrap()[4..].to_vec()
}

fn host_theme(update: ClientHostThemeUpdate) -> ClientMessage {
    ClientMessage::ClientShellHostTheme { update }
}

#[test]
fn host_theme_updates_match_independent_source_layout() {
    // Hand-written bincode 2 standard, following herdr src/protocol/wire.rs:
    // message tag 17, update tag (DefaultColor 0, PaletteColors 1, Appearance 2),
    // then the payload fields in declaration order. Not generated by our model.
    let color = ClientHostColor {
        r: 0x2e,
        g: 0x34,
        b: 0x40,
    };
    for (message, fixture) in [
        (
            host_theme(ClientHostThemeUpdate::DefaultColor {
                kind: ClientHostDefaultColorKind::Foreground,
                color,
            }),
            vec![17, 0, 0, 0x2e, 0x34, 0x40],
        ),
        (
            host_theme(ClientHostThemeUpdate::DefaultColor {
                kind: ClientHostDefaultColorKind::Background,
                color,
            }),
            vec![17, 0, 1, 0x2e, 0x34, 0x40],
        ),
        (
            host_theme(ClientHostThemeUpdate::PaletteColors(vec![
                (4, color),
                (255, ClientHostColor { r: 1, g: 2, b: 3 }),
            ])),
            vec![17, 1, 2, 4, 0x2e, 0x34, 0x40, 255, 1, 2, 3],
        ),
        (
            host_theme(ClientHostThemeUpdate::Appearance(
                ClientHostAppearance::Dark,
            )),
            vec![17, 2, 0],
        ),
        (
            host_theme(ClientHostThemeUpdate::Appearance(
                ClientHostAppearance::Light,
            )),
            vec![17, 2, 1],
        ),
    ] {
        assert_eq!(payload(&message), fixture, "{message:?}");
        assert_eq!(decode_payload::<ClientMessage>(&fixture).unwrap(), message);
    }
}

#[test]
fn full_palette_fits_one_frame_with_a_varint_length() {
    let colors: Vec<_> = (0..=u8::MAX)
        .map(|index| {
            (
                index,
                ClientHostColor {
                    r: index,
                    g: 0,
                    b: 0,
                },
            )
        })
        .collect();
    let message = host_theme(ClientHostThemeUpdate::PaletteColors(colors));
    let bytes = payload(&message);
    // 256 needs bincode's u16 varint marker (251) and little-endian length.
    assert_eq!(bytes[..5], [17, 1, 251, 0, 1]);
    assert_eq!(bytes.len(), 5 + 256 * 4);
    assert_eq!(decode_payload::<ClientMessage>(&bytes).unwrap(), message);
}

#[test]
fn malformed_host_theme_updates_fail_closed() {
    for bytes in [
        // Unknown update, default color kind, and appearance tags.
        &[17, 3][..],
        &[17, 0, 2, 0, 0, 0],
        &[17, 2, 2],
        // Truncated color and palette entry.
        &[17, 0, 0, 1, 2],
        &[17, 1, 1, 4, 1, 2],
        // A palette index outside u8.
        &[17, 1, 1, 251, 0, 1, 0, 0, 0],
    ] {
        assert!(
            decode_payload::<ClientMessage>(bytes).is_err(),
            "{bytes:?} decoded"
        );
    }
    assert!(matches!(
        decode_payload::<ClientMessage>(&[17, 2, 0, 0]),
        Err(Error::TrailingBytes)
    ));
}
